# Generated by Django 5.1.1 on 2024-10-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_claim_probability'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.TextField(blank=True, null=True)),
                ('case_year', models.TextField(blank=True, null=True)),
                ('petitioner', models.TextField(blank=True, null=True)),
                ('respondent', models.TextField(blank=True, null=True)),
                ('unique_case_number', models.TextField(blank=True, null=True)),
                ('cnr', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('court_complex', models.TextField(blank=True, null=True)),
                ('case_type', models.TextField(blank=True, null=True)),
                ('filing_date', models.TextField(blank=True, null=True)),
                ('regi_number', models.TextField(blank=True, null=True)),
                ('first_hearing_date', models.TextField(blank=True, null=True)),
                ('decision_date', models.TextField(blank=True, null=True)),
                ('hearing_count', models.TextField(blank=True, null=True)),
                ('nature_of_disposal', models.TextField(blank=True, null=True)),
                ('court_number_and_judge', models.TextField(blank=True, null=True)),
                ('petitioner_advocate', models.TextField(blank=True, null=True)),
                ('respondent_advocate', models.TextField(blank=True, null=True)),
                ('under_act', models.TextField(blank=True, null=True)),
                ('under_section', models.TextField(blank=True, null=True)),
                ('incident_details', models.TextField(blank=True, null=True)),
                ('claim_amount', models.TextField(blank=True, null=True)),
                ('settlement_amount', models.TextField(blank=True, null=True)),
                ('interest_rate', models.TextField(blank=True, null=True)),
                ('payment_mode', models.TextField(blank=True, null=True)),
                ('judge_name', models.TextField(blank=True, null=True)),
                ('summary_of_pdf', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
